### ISSUE TITLE
Port status filtering

### ISSUE THREAD

**Issue by roo7break** [vdbaan/IssueFinder#13]
Can you add port status as a column and filter option?

**Comment by vdbaan** [comment]
I'm doubting between implementing this or changing the port display to <port nr>/<state>/<protocol>. With the latter option you can easier mix/mash within filters.
For example using open,22 would show all ports that are open (tcp and udp) or have the number 22 in their port number. I'd like to have your input on that too.

**Comment by roo7break** [comment]
Steven,

First, you could do with splitting the port to numbers and status. Secondly, I think text based matching could be easier as port number, status and protocol are in that field, like you mentioned above. But do make sure we can add and subtract filter options.
