### ISSUE TITLE
Pre-built filter reports

### ISSUE THREAD

**Issue by roo7break** [vdbaan/IssueFinder#20]
Adding pre-built filters would we really useful. Examples include- Show open ports, show IPs with open ports, show most vulnerable hosts, show most vulnerable services, etc. 

These can be shown in a pop-up window, one item per line. 

Will help when adding to reports

**Comment by vdbaan** [comment]
Sounds like a good addition. Will add them in the drop-down list for the filters.

**Comment by vdbaan** [comment]
I will not add it as filters, but I'll add a statistics page that will show the following in a tree table view, looking roughly like this:
```
- IPs (3)
  - 192.168.0.1
    - open ports (12)                                22,80,81,8080,<etc>
    - highest vulnerability (1 CRITICAL)    
      - <affected service>                            <Name of plugin>
    - found services                                  ssh,http,<etc>
  - 192.168.0.2
    - open ports
    + highest vulnerability (3 HIGH)        
    - found services
  + 192.168.0.3 <can expand>

```
This information will be based on what is in view.
