### ISSUE TITLE
Nessie viewer feature request

### ISSUE THREAD

**Issue by anantshri** [vdbaan/IssueFinder#29]
While this tool has clearly added more support then nessie viewer and has better capabilities. There is one feature which makes me remember nessie viewer. The current filters are typing focused and would be awesome if we can have may be some of the filters present in like a drop down fashion.

This is how nessie viewer does filtering.
![nessie_viewer](https://user-images.githubusercontent.com/236843/35547319-5e406d02-059e-11e8-9f83-e95a44767faf.png)

What i am proposing is just below the filter text box we place some common placeholders like risk rating. Host, port, plugin id / name etc so people can just select from drop down and done. I know there is a round about way right now where people can right click on specific item and select it as filter simmilar to how wireshark does it but a drop down autopopulated based on whatever we have on record will be a awesome.

hoping this does gets added as a feature.

**Comment by vdbaan** [comment]
I'm thinking of combining this with the current way of filtering. I'll add a 'Build ...' option in the pull down menu, like this:
![image](https://user-images.githubusercontent.com/2207005/35556844-519651dc-059b-11e8-8f9d-73f7c007838d.png)

When selecting that you have the ability to build the filter as you describe. It will open the following in a separate dialog:
![image](https://user-images.githubusercontent.com/2207005/35568904-6c590222-05c2-11e8-963f-a2fffc895072.png)
