### ISSUE TITLE
Add CSV and IVIL export functionality 

### ISSUE THREAD

**Issue by vdbaan** [vdbaan/IssueFinder#6]

**Comment by rebootuser** [comment]
Any chance this may be added in the near future? Failing a csv/txt export option, it would be great to have copy functionality for X selected columns to transfer data into other programs for parsing, formatting etc.

**Comment by vdbaan** [comment]
I have some time now, so I will try to do this soon.

**Comment by rebootuser** [comment]
New functionality is useful indeed. I see that the summary can't added as a column and hence can't be exported. Is there a possibility this could be added? Sometimes it's great to get this info in one hit, i.e. export to CSV > import into Excel > add column filters > select device hostname finding and see the related summary detailing the device hostname, for example.
